name: Github Actions Demo
on:
    push:
        branches:
            dev
env:
   IMAGE_NAME: custom

jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v2
           - name: Build image
             run: docker build . --file Dockerfile --tag $IMAGE_NAME
           - name: Loggin
             run: echo "${{secrets.KEY}}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
           - name: push
             run: |
               IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME 
               docker tag $IMAGE_NAME $IMAGE_ID:v${{ github.run_id }}-dev
               docker push $IMAGE_ID:V${{ github.run_id }}-dev 


# ${{ secrets.KEY }}